name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  installing-linearalgebraasimjalwana0123:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - uses: actions/checkout@v4
      #----------------------------------------------
      #   install & configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --no-root
      #----------------------------------------------
      # run tests
      #----------------------------------------------
      - name: run tests
        run: poetry run pytest -v
      #----------------------------------------------
      #  poetry build and publish
      #----------------------------------------------
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ vars.PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"